name: ci

on: [push, workflow_call]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-test-env
      - name: Build JS
        run: pnpm build
      - name: Run Tests
        run: pnpm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-test-env
      - name: Run Lint
        run: pnpm run lint

  automerge:
    needs: [build, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v1
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        with:
          github-token: ${{secrets.github_token}}
