name: ci

on: [push, workflow_call]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-test-env
      - name: Build JS
        run: yarn build
      - name: Run Tests
        run: yarn run test
      - name: Run Lint
        run: yarn run lint

  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v1
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        with:
          github-token: ${{secrets.github_token}}
